### ISSUE TITLE
FilterDiscoMetadata: duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by corralee** [JinmiaoChenLab/DISCOtoolkit_py#8]
Hi,

Thank you for this great resource.

While running `FilterDiscoMetadata` function, I got the following error: `Error in '.rowNamesDF<-'(x, value = value) : duplicate 'row.names' are not allowed`

This is likely related to some samples (15306, 15308, 15310, 15312, 15314, 15316) not having an assigned id in the latest sample metadata table. In case someone runs into the same issue, I overcame it by updating the function to exclude these samples after fetching the metadata.
```
message("Fetching sample metadata")
metadata = read.csv(paste0(getOption("disco_url"), "toolkit/getSampleMetadata"), sep = "\t")
metadata = metadata[!duplicated(metadata$sample_id),]
rownames(metadata) = metadata$sample_id`
```

Kind regards!

**Comment by lmw123** [comment]
Hi Corrales,

Thank you for pointing out this issue! We'll update the data as soon as possible.

Best regards,
Mengwei

**Comment by lmw123** [comment]
@corralee 
Hi Corrales,

We’ve resolved the issue you mentioned, which was caused by the presence of "\n" in the metadata table. We sincerely apologize for any inconvenience this may have caused and greatly appreciate you bringing this to our attention.

Thank you again for your valuable feedback. We are committed to continually improving the DISCO toolkit to enhance your experience.

Best regards,
Mengwei

**Comment by corralee** [comment]
Hi Mengwei,

Thank you for resolving the issue and for the detailed explanation. I’m very grateful.

Kind regards,

Eyleen
